### ISSUE TITLE
关于C++中std::map<std::string,std::string>使用爆错的问题

### ISSUE THREAD

**Issue by guangmingzhengda** [BUAA-Soft-2023-Summer/Soft-Summer-2023#10]
命名中均用英文字符命名，输出时为了减少转化的工作量，我在Globals.cpp中开了一个```std::map<std::string,std::string> Trans```的map，但是在赋值```Trans[L"Caocao"]=L"曹操"```时报错
![QQ截图20230825214455](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/c0454211-6afd-4835-838b-b2df1b3d6b6c)
这种做法我在Dev中使用是无误的，请问问题是在于定义的位置不对，抑或是其他问题呢？
谢谢学长！

**Comment by Lord-Turmoil** [comment]
我这里似乎 Dev-C++（使用 `-std=c++11`）和 Visual Studio 都不可以。

因为 `std::map` 不是数组，所以可能不支持这样的写法，把它封装到一个初始化函数里吧。

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/23f7c425-4d9c-4669-bb18-cc9d2b1afe12)

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/db241bc1-0a0b-4c42-ba56-7ceb1b5a302d)

**Comment by guangmingzhengda** [comment]
> 我这里似乎 Dev-C++（使用 `-std=c++11`）和 Visual Studio 都不可以。
> 
> 因为 `std::map` 不是数组，所以可能不支持这样的写法，把它封装到一个初始化函数里吧。
> 
> ![image](https://user-images.githubusercontent.com/68287135/263423751-23f7c425-4d9c-4669-bb18-cc9d2b1afe12.png)
> 
> ![image](https://user-images.githubusercontent.com/68287135/263423756-db241bc1-0a0b-4c42-ba56-7ceb1b5a302d.png)

谢谢学长，按照此方式可以顺利通过编译，但是却无输出我初始化`
	Trans[L"Wufangjv"] = L"无防具";`后，使用如下代码：
![QQ截图20230826110610](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/47eb5059-2912-4a5b-a489-75d1f032fbac)
却得到如下效果：
![QQ截图20230826110754](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/a12c06ef-64cf-487b-abc9-765fda035e17)
请问是我在初始化中的问题还是使用时的问题呢？

**Comment by Lord-Turmoil** [comment]
提供的代码片段太少，我无法得知你初始化的信息。

**Comment by guangmingzhengda** [comment]
在`main.cpp`中进行了初始化，在`Globals.h`中进行了定义
![QQ截图20230826111911](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/ee1a4dfa-defc-42ca-99c8-0c2f476ce03f)
![QQ截图20230826111923](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/7f21d5f5-72d3-49f1-a4b0-1befdcf1e18e)

**Comment by Lord-Turmoil** [comment]
打断点呀，看看这个地方的值是什么。

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/785bbb7c-1396-4700-a6a6-e7ba52ec531b)

还有，用这个 `setbkmode(TRANSPARENT)` 设置文字背景为透明色。

**Comment by guangmingzhengda** [comment]
好的谢谢学长！我发现在`main`中初始化后，在我调用时`Trans`又清空了，目前不知道是什么原因，但是有一种解决办法是在`GameInterface.cpp`中再进行初始化，可以解决当前问题，谢谢学长！
