### ISSUE TITLE
unity中预制体生成的敌人检测玩家的位置

### ISSUE THREAD

**Issue by hirmy** [BUAA-Soft-2023-Summer/Soft-Summer-2023#12]
请问预制体生成的敌人想获取非预制体的玩家的位置，该如何实现呢
![f8cc034dea77bf2aec09e48997c28ff](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/141300388/cd435b9f-4323-45f2-a4c8-6c3a671011dd)
![a8a70d5f0d88ba7469e4ef371863d1b](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/141300388/c7bc2fbe-8b7a-4c23-ae24-2f4cc8ac8c4b)

**Comment by yizhiqianbi** [comment]
使用getcomponent方法
