### ISSUE TITLE
Java游戏界面内使图像旋转

### ISSUE THREAD

**Issue by void-CrowD** [BUAA-Soft-2023-Summer/Soft-Summer-2023#13]
如何在Java的图形化界面内实现一个旋转图片？
<img width="147" alt="image" src="https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/142764918/acf02701-b24a-4a98-8d53-f02410c6efd0">
比如黄金矿工里面的钩爪，需要使其随着绳子的摆动而转动而不是简单的跟随效果

**Comment by BigBigZhe** [comment]
如果是用swing或者awt可以使用Graphics类的rotate函数将其旋转
