### ISSUE TITLE
Java批量读取图片并应用于动画

### ISSUE THREAD

**Issue by void-CrowD** [BUAA-Soft-2023-Summer/Soft-Summer-2023#14]
<img width="88" alt="image" src="https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/142764918/aa5fad69-8572-47f0-a4e5-17bf17de61f6">
我将一个动画的帧图片按顺序存储在本地文件夹中，怎样高效的读取并且在Java内赋给变量以使用？

**Comment by BigBigZhe** [comment]
初始化程序的时候加载完就行，速度不会很慢的
需要遍历每个图片用ImageIO加载放到一个list里面
import javax.imageio.ImageIO;
Image image = ImageIO.read(new File(filepath));
每次绘制改一下index然后用Graphics的drawImage绘制出来
drawImage(ImgList.get(index), 0, 0, width, height, null);
