### ISSUE TITLE
Java在游戏中引入音效

### ISSUE THREAD

**Issue by void-CrowD** [BUAA-Soft-2023-Summer/Soft-Summer-2023#18]
CSDN有很多博客，但是很多都在我的电脑上报错，电脑没有安装什么Sun JDK以及其他的文件，有没有能直接引入音频的方法？

**Comment by BigBigZhe** [comment]
Java内置的只有javax.sound，如果你的JDK里面没有那就只能引入这个库或者其他库，引入的方法可以是直接jar包引入或者Maven、Gradle

**Comment by BUAAwei** [comment]
可以看之前issue中我的回答，我给过一个MusicPlayer类，很多同学用过，反应较好，我在这里再给你粘贴一份
[MusicPlayer.md](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/files/12481273/MusicPlayer.md)
