### ISSUE TITLE
C++ EasyX已安装fmod模块，报错无法找到fmod.dll

### ISSUE THREAD

**Issue by guangmingzhengda** [BUAA-Soft-2023-Summer/Soft-Summer-2023#19]
如下图所示，已按照教程在相应位置添加fmod中的第三方库和链接库，但是运行仍提示无法找到fmod.dll，请问可能是哪种原因，谢谢！
![QQ截图20230831085048](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/a02532c0-7401-4c99-ae8e-37892f7013c8)

**Comment by Lord-Turmoil** [comment]
这个属于已经成功运行程序了，只是在程序**运行目录**没有找到 `fmod.dll`。需要把它放在你设置好的工作目录中。

**Comment by guangmingzhengda** [comment]
请问能否详细解释一下何为**放在设置好的工作目录**中，应该不是指的`限定在此项目中`的选项吧，`lib`文件夹应该放在和`inc`等并列的位置吧

**Comment by Lord-Turmoil** [comment]
你使用了 FMOD，它会在程序启动时寻找当前目录中的 `fmod.dll`，因此你需要在工作目录里包含它。

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/bcbdd47d-63b9-423b-8f8a-55ea455e55ef)

视频中应该有完整的介绍，包括使用 Post-Build Event 拷贝相关文件到工作目录，就在[添加声音](https://www.bilibili.com/video/BV1Wr4y1Z7aX?p=11)这一节，你可以详细看一下。

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/2e14d033-7207-4409-813b-f301f7193019)

**Comment by guangmingzhengda** [comment]
好的好的，谢谢学长，我尝试一下！
