### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by xuexia004** [BUAA-Soft-2023-Summer/Soft-Summer-2023#2]
### 问题
java怎么实现音频的播放

### 环境

- Windows 11

- IDEA 2021

**Comment by BUAAwei** [comment]
可以使用javax.sound实现简单音频播放（目前本方法识别wav文件正常，其他格式的音频文件可能出现问题，建议将音频文件转为wav文件后使用）
[MusicPlayer.md](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/files/12416099/MusicPlayer.md)
