### ISSUE TITLE
C语言如何通过for循环loadimage()批量加载多个图片

### ISSUE THREAD

**Issue by Cirno0416** [BUAA-Soft-2023-Summer/Soft-Summer-2023#3]
IMAGE cards[8];
for(int i=0;i<8;i++)
{
	loadimage(&cards[i],_T("res\\Cards\\card_i.png"));
}
图片文件名参数"card_0.png"~"card_7.png"应该怎么定义

**Comment by huangjianbuaa** [comment]
字符串拼接呀，把“res\Cards\card_" 和变量 i 和 ".png" 拼起来
