### ISSUE TITLE
Unity地图制作

### ISSUE THREAD

**Issue by zengqile** [BUAA-Soft-2023-Summer/Soft-Summer-2023#4]
### 问题：
![map](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/99401829/d52e40bd-5bba-431a-be3f-72067df9f329)
  大板块为三个小板块，大板块通过桥连接，棋子通过相邻的小板块或桥移动，如何将上图制作为地图让棋子行动。
### 环境：

- Unity2022 
- win10 
- vscode

**Comment by yizhiqianbi** [comment]
实现方法挺多，如果仅仅针对固定地图也可以考虑用图算法
也可以考虑添加connectComponent，每板块添加此component，这个component里面维护个list，list中存可以走的对象，都是比较好实现的

**Comment by Abyss7893** [comment]
你可以把每一个小板块绑定一个事件，点击事件后进入对应的关卡。然后在逻辑中制定关卡顺序，在通关前一个关卡之后自动解锁下一个关卡。如果想实现棋子移动动画的话，可以在通关后加判断当前关卡的位置和下一关关卡的位置，然后加动画实现两个位置的移动即可。
