### ISSUE TITLE
Visual Studio用C++画图时报错

### ISSUE THREAD

**Issue by guangmingzhengda** [BUAA-Soft-2023-Summer/Soft-Summer-2023#6]
仿照学长给的操作模式出现了这样的问题，请问该如何解决呢/kel
![QQ截图20230825131348](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/108414129/3d3f6450-4096-42cb-80c9-09883a205828)

**Comment by Lord-Turmoil** [comment]
能提供更多信息吗？从这里看不出太多东西。

一个可能的原因是，设备初始化问题，是否有最开始有 `initgraph` ？

**Comment by guangmingzhengda** [comment]
在main函数中有进行```initgraph```，仿照学长在GameInterface中的画图行为，添加到了自己写的GameObject中的Draw就出现了上述问题

**Comment by Lord-Turmoil** [comment]
你是否设置了项目字符集为 `Unicode`？

**Comment by guangmingzhengda** [comment]
设置过了，这段绘制代码在GameInterface中就能正常运行，复制粘贴到GameObject中就出现此问题了

**Comment by Lord-Turmoil** [comment]
注释掉该语句，是否能正常运行？

**Comment by guangmingzhengda** [comment]
注释掉该行，下一行会继续报错，继续注释下一行，再下一行爆错，直至全部注释掉

**Comment by Lord-Turmoil** [comment]
你的程序中是否有**内存泄漏**问题？或是使用 `SetWorkingImage` 时忘记切换回默认设备？

**Comment by guangmingzhengda** [comment]
emmm抱歉我不太清楚**内存泄漏**指的是什么意思

**Comment by Lord-Turmoil** [comment]
你是否在删除了这个对象后，仍调用了这个方法？尤其注意在遍历列表时的删除操作。

如果无法解决，可以将项目源代码打包，我看一下。（只打包 `.sln` 和工程目录，并且删掉所有临时文件和目录。）

**Comment by guangmingzhengda** [comment]
好的我先检查一下，实在搞不定再发给您，谢谢学长

**Comment by guangmingzhengda** [comment]
> 你是否在删除了这个对象后，仍调用了这个方法？尤其注意在遍历列表时的删除操作。
> 
> 如果无法解决，可以将项目源代码打包，我看一下。（只打包 `.sln` 和工程目录，并且删掉所有临时文件和目录。）
[Sanguosha.zip](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/files/12436081/Sanguosha.zip)
主要问题在于GameObject的绘制时出现问题，谢谢学长！

**Comment by Lord-Turmoil** [comment]
你似乎“意外”地在 `GameInterface` 的构造函数里调用了绘制，但是这个构造函数在 `Main` 函数中的 `Init` 里，`initgraph` 之前。所以问题就出在这里。

![image](https://github.com/BUAA-Soft-2023-Summer/Soft-Summer-2023/assets/68287135/3991fb48-a4a3-423b-844b-eb92eb663e35)


> 能提供更多信息吗？从这里看不出太多东西。
> 
> 一个可能的原因是，设备初始化问题，是否有最开始有 `initgraph` ？

**Comment by guangmingzhengda** [comment]
> 你似乎“意外”地在 `GameInterface` 的构造函数里调用了绘制，但是这个构造函数在 `Main` 函数中的 `Init` 里，`initgraph` 之前。所以问题就出在这里。
> 
> ![image](https://user-images.githubusercontent.com/68287135/263187819-3991fb48-a4a3-423b-844b-eb92eb663e35.png)
> 
> > 能提供更多信息吗？从这里看不出太多东西。
> > 一个可能的原因是，设备初始化问题，是否有最开始有 `initgraph` ？

原来如此，谢谢学长！我现在明白了
